### ISSUE TITLE
Bug: <template> cannot be placed not in first place of SFC

### ISSUE THREAD

**Issue by Grawl** [Shinigami92/eslint-plugin-vue-pug-sfc#128]
If I place `<template>` tag in first place of SFC, `eslint-plugin-vue-pug-sfc` shows me the right error in the right place. I'm very happy to finally lint my Pug code in Vue SFC!

But if I place `<template>` after `<script>`, error shows me the wrong place of lint warning. It shows the place where warning will be if template placed on the first place of SFC.

## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | 1.0.0-alpha.15                  |
| Eslint    | v6.8.0                  |
| Node      | v14.18.0                  |
| OS        | mac           |

## Eslint config

```js
module.exports = {
	root: true,
	env: {
		node: true,
	},
	parserOptions: {
		parser: 'babel-eslint',
	},
	extends: [
		'plugin:vue/vue3-essential',
		'eslint:recommended',
		'plugin:vue-pug-sfc/recommended',
	],
	plugins: [
		'vue',
	],
}
```

## Input

```vue
<script>
import { defineComponent } from 'vue'

export default defineComponent({
	data: () => ({
		list: [
			'a', 'b', 'c',
		],
	}),
})
</script>
<template lang='pug'>
div
	span(v-for='item in list') {{ item }}
</template>
```

## Output or Error

```bash
error: Elements in iteration expect to have 'v-bind:key' directives (vue-pug-sfc/require-v-for-key) at src/App.vue:3:7:
  1 | <script>
  2 | import { defineComponent } from 'vue'
> 3 |
    | ^
  4 | export default defineComponent({
  5 |   data: () => ({
  6 |           list: [
```

## Expected Output

```bash
error: Elements in iteration expect to have 'v-bind:key' directives (vue-pug-sfc/require-v-for-key) at src/App.vue:14:7:


  12 | <template lang='pug'>
  13 | div
> 14 | 	span(v-for='item in list') {{ item }}
             ^
  15 | </template>
```

## Additional Context

I created a repository to demonstrate this bug (and other/future bugs maybe), here is two commits I pushed:

1. [`init`](https://github.com/Grawl/eslint-plugin-vue-pug-sfc-demo/tree/2aa3c9f33ada0f15befdeb75f9a95bc54937decd) shows the right place of lint warning because template tag is placed on the first place
2. [`demonstrate eslint-plugin-vue-pug-sfc bug`](https://github.com/Grawl/eslint-plugin-vue-pug-sfc-demo/tree/010dec6af6444da52ef234259fe8d3529db28521) shows misplaced lint warning because template tag is placed after script

**Comment by Shinigami92** [comment]
Please try https://github.com/Shinigami92/eslint-plugin-vue-pug-sfc/releases/tag/1.0.0-alpha.17

**Comment by Grawl** [comment]
I can confirm this bug is fixed https://github.com/Grawl/eslint-plugin-vue-pug-sfc-demo/tree/476454ac8929f776db25cbfe4bed99e2d35ec95c
