### ISSUE TITLE
Bug: crash on slot

### ISSUE THREAD

**Issue by sid-6581** [Shinigami92/eslint-plugin-vue-pug-sfc#135]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | 1.0.0-alpha.18                  |
| Eslint    | 8.4.1                  |
| Node      | 17.2.0                  |
| OS        | Windows 11           |

## Eslint config

```js
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: [
    "plugin:vue/recommended",
    "plugin:vue-pug-sfc/recommended",
    "plugin:prettier/recommended",
    "eslint:recommended",
    "@vue/typescript/recommended",
    "prettier",
  ],
  parser: "vue-eslint-parser",
  parserOptions: {
    parser: "@typescript-eslint/parser",
    ecmaVersion: 2020,
    vueFeatures: {
      filter: true,
      interpolationAsNonHTML: false,
    },
  },
  rules: {
    "@typescript-eslint/no-shadow": "error",
    "@typescript-eslint/no-non-null-assertion": "off",
    "no-shadow": "off",
    "no-await-in-loop": "off",
    "no-console": process.env.NODE_ENV === "production" ? "warn" : "off",
    "no-debugger": process.env.NODE_ENV === "production" ? "warn" : "off",
    "prefer-destructuring": ["error", { object: false, array: false }],
    "max-classes-per-file": "off",
    "no-restricted-syntax": "off",
    "no-unused-expressions": "off",
    "arrow-body-style": ["error", "as-needed"],
    "no-plusplus": "off",
    "lines-between-class-members": ["error", "always", { exceptAfterSingleLine: true }],
    "vue/multi-word-component-names": "off",
    "vue-pug-sfc/component-name-in-template-casing": ["warn", "kebab-case"],
    "vue/html-self-closing": [
      "error",
      {
        html: {
          void: "always",
          normal: "always",
          component: "always",
        },
        svg: "always",
        math: "always",
      },
    ],
    "no-nested-ternary": "off",
    "no-return-assign": "off",
    "prettier/prettier": [
      "warn",
      {
        tabWidth: 2,
        printWidth: 150,
        pugAttributeSeparator: "none",
        pugSortAttributes: "asc",
        pugEmptyAttributes: "none",
      },
    ],
  },
};
```

## Input

```vue
<template lang="pug">
div
  span(v-if="true")
  slot
</template>
```

## Output or Error

```bash
 ERROR  Failed to compile with 1 error

 error

Cannot read properties of undefined (reading 'includes')
Occurred while linting [..]/FormField.vue:8
Rule: "vue-pug-sfc/this-in-template"
```

## Expected Output

No error

## Additional Context

This appears to crash on `attr.name.includes('v-if')` in `valid-v-else-if.js` because of the slot. I can work around it by inserting a dummy template before the slot:

```vue
<template lang="pug">
div
  span(v-if="true")
  template
  slot
</template>
```

**Comment by Shinigami92** [comment]
I'm not sure if I can tackle these bugs in the winter holidays. But please feel free and try to create a PR, I can help with reviews and I would be very happy if some folks like you gets your hand dirty on my code-base :slightly_smiling_face:

**Comment by sid-6581** [comment]
Frontend isn't my specialty, but I will take a look and try. ☺️

**Comment by Shinigami92** [comment]
> Frontend isn't my specialty, but I will take a look and try. relaxed

Actually this part is not frontend :smile:  
But yeah, this would be really nice and helpful.

**Comment by Shinigami92** [comment]
You should first add a test-case here: https://github.com/Shinigami92/eslint-plugin-vue-pug-sfc/blob/main/tests/rules/valid-v-else-if.test.ts
Then fix it in https://github.com/Shinigami92/eslint-plugin-vue-pug-sfc/blob/main/src/rules/valid-v-else-if.ts

If anything is unclear, please ask and I can try to help and potentially later write contribution documentation based on that.

**Comment by sid-6581** [comment]
I found the problem and fixed it, so I'll have a PR up in a bit! You've done a great job at making it easy to contribute.

**Comment by Shinigami92** [comment]
Both fixes released in [v1.0.0-alpha.19](https://www.npmjs.com/package/eslint-plugin-vue-pug-sfc/v/1.0.0-alpha.19)
I really like your contribution and would love to see more from you in the future if you like.
Thank you for bringing this project forward.

**Comment by sid-6581** [comment]
Thank you for the quick turnaround! Yes, I would love to contribute. I have one other issue that I thought one of the PRs would take care of, but it seems to be a different issue. I'll look at that one in a bit and will probably put up a PR for that as well. I'll also try to familiarize myself more with the codebase and see about porting over some more rules. Thanks a lot for your great work, your projects are incredibly useful!

**Comment by Shinigami92** [comment]
I invited you into this repo
You can now delete your fork and use this repo directly. Still need to create PRs, cause you cannot write into main, but we can now work more easily together on code that way :)

**Comment by sid-6581** [comment]
Thank you! I looked at the issue I thought was remaining, but I guess it was just something not fully updated in my project that used the package, because the issue was indeed fixed by the second PR. I'll look at other things then. Is there anything in particular you think is high priority?

**Comment by Shinigami92** [comment]
I have a project board: https://github.com/Shinigami92/eslint-plugin-vue-pug-sfc/projects/1

If you like to, you can have a look into the `Needs improvement` section
Otherwise I will move some new into the `Prioritize next` column :slightly_smiling_face:
